-- CREATING EACH TABLE IN THE ACADEMIC DATABASE
CREATE TABLE ACADEMIC_SESSION
(
SESSION_ID NUMBER NOT NULL ,
SESSION_NAME VARCHAR2(50)
) ;

CREATE TABLE COURSE
(
COURSE_ID NUMBER NOT NULL ,
COURSE_NAME VARCHAR2 (50) ,
SESSION_ID NUMBER ,
DEPARTMENT_ID NUMBER
) ;

CREATE TABLE DEPARTMENT
(
DEPARTMENT_ID NUMBER NOT NULL ,
DEPARTMENT_NAME VARCHAR2(50) ,
HOD VARCHAR2(50)
) ;

CREATE TABLE EXAM_DETAIL
(
EXAM_ID NUMBER NOT NULL ,
EXAM_TYPE VARCHAR2(50) NOT NULL ,
START_DATE DATE ,
NAME VARCHAR2(50)
) ;

CREATE TABLE EXAM_RESULT
(
STUDENT_ID NUMBER NOT NULL,
EXAM_ID NUMBER NOT NULL,
COURSE_ID NUMBER NOT NULL,
GRADE NUMBER
) ;

CREATE TABLE EXAM_TYPE
(
EXAM_TYPE VARCHAR2(50) NOT NULL ,
EXAM_NAME VARCHAR2(50) ,
EXAM_DESC VARCHAR2(50)
) ;

CREATE TABLE FACULTY_COURSE
(
FACULTY_ID NUMBER NOT NULL,
COURSE_ID NUMBER NOT NULL
) ;

CREATE TABLE FACULTY
(
FACULTY_ID NUMBER NOT NULL ,
FACULTY_NAME VARCHAR2(50) ,
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50)
) ;

CREATE TABLE FACULTY_LOGIN
(
FACULTY_ID NUMBER NOT NULL,
LOGIN_DATE DATE NOT NULL,
LOGIN_TIME DATE NOT NULL,
DETAILS VARCHAR2(50)
) ;

CREATE TABLE PARENT_INFORMATION
(
PARENT_ID NUMBER NOT NULL ,
FATHER_NAME VARCHAR2(50) ,
MOTHER_NAME VARCHAR2(50)
) ;

CREATE TABLE STUDENT_ATTENDANCE
(
STUDENT_ID NUMBER NOT NULL,
NO_OF_WORKING_DAYS NUMBER ,
NO_OF_DAYS_OFF NUMBER ,
ELIGIBILITY_FOR_EXAMS CHAR
) ;

CREATE TABLE STUDENT_COURSE
(
STUDENT_ID NUMBER ,
COURSE_ID NUMBER 
) ;

CREATE TABLE STUDENT
(
STUDENT_ID NUMBER NOT NULL ,
FIRST_NAME VARCHAR2(50) ,
PARENT_ID NUMBER,
STUDENT_REG_YEAR DATE
) ;

-- ADDING PRIMARY KEYS TO EACH TABLE
ALTER TABLE ACADEMIC_SESSION ADD CONSTRAINT ACADEMIC_SESSION_PK PRIMARY KEY ( SESSION_ID ) ;
ALTER TABLE COURSE ADD CONSTRAINT COURSE_PK PRIMARY KEY ( COURSE_ID ) ;
ALTER TABLE DEPARTMENT ADD CONSTRAINT DEPARTMENT_PK PRIMARY KEY ( DEPARTMENT_ID ) ;
ALTER TABLE EXAM_DETAIL ADD CONSTRAINT EXAM_DETAIL_PK PRIMARY KEY ( EXAM_ID ) ;
ALTER TABLE EXAM_TYPE ADD CONSTRAINT EXAM_TYPE_PK PRIMARY KEY ( EXAM_TYPE ) ;
ALTER TABLE FACULTY ADD CONSTRAINT FACULTY_PK PRIMARY KEY ( FACULTY_ID ) ;
ALTER TABLE PARENT_INFORMATION ADD CONSTRAINT PARENT_INFORMATION_PK PRIMARY KEY ( PARENT_ID ) ;
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_PK PRIMARY KEY ( STUDENT_ID ) ;
ALTER TABLE STUDENT_ATTENDANCE ADD CONSTRAINT STUDENT_ATTENDANCE_PK PRIMARY KEY ( STUDENT_ID )  ;
ALTER TABLE EXAM_RESULT ADD CONSTRAINT EXAM_RESULT_PK PRIMARY KEY ( STUDENT_ID, COURSE_ID, EXAM_ID )  ;
ALTER TABLE FACULTY_LOGIN ADD CONSTRAINT FACULTY_LOGIN_PK PRIMARY KEY ( FACULTY_ID, LOGIN_DATE, LOGIN_TIME )  ;
ALTER TABLE FACULTY_COURSE ADD CONSTRAINT FACULTY_COURSE_PK PRIMARY KEY ( FACULTY_ID, COURSE_ID )  ;
ALTER TABLE STUDENT_COURSE ADD CONSTRAINT STUDENT_COURSE_PK PRIMARY KEY ( STUDENT_ID, COURSE_ID)  ;

-- ADDING FOREIGN KEYS TO EACH TABLE
ALTER TABLE COURSE ADD CONSTRAINT COURSE_FK FOREIGN KEY ( SESSION_ID ) REFERENCES ACADEMIC_SESSION ( SESSION_ID ) ;
ALTER TABLE COURSE ADD CONSTRAINT COURSE_FKv2 FOREIGN KEY ( DEPARTMENT_ID ) REFERENCES DEPARTMENT ( DEPARTMENT_ID ) ;
ALTER TABLE EXAM_DETAIL ADD CONSTRAINT EXAM_DETAIL_FK FOREIGN KEY ( EXAM_TYPE ) REFERENCES EXAM_TYPE ( EXAM_TYPE ) ;
ALTER TABLE EXAM_RESULT ADD CONSTRAINT EXAM_RESULT_FK FOREIGN KEY ( COURSE_ID ) REFERENCES COURSE ( COURSE_ID ) ;
ALTER TABLE EXAM_RESULT ADD CONSTRAINT EXAM_RESULT_FKv2 FOREIGN KEY ( EXAM_ID ) REFERENCES EXAM_DETAIL ( EXAM_ID ) ;
ALTER TABLE EXAM_RESULT ADD CONSTRAINT EXAM_RESULT_FKv3 FOREIGN KEY ( STUDENT_ID ) REFERENCES STUDENT ( STUDENT_ID ) ;
ALTER TABLE FACULTY_COURSE ADD CONSTRAINT FACULTY_COURSE_FK FOREIGN KEY ( FACULTY_ID ) REFERENCES FACULTY ( FACULTY_ID ) ;
ALTER TABLE FACULTY_COURSE ADD CONSTRAINT FACULTY_COURSE_FKv2 FOREIGN KEY ( COURSE_ID ) REFERENCES COURSE ( COURSE_ID ) ;
ALTER TABLE FACULTY_LOGIN ADD CONSTRAINT FACULTY_LOGIN_FK FOREIGN KEY ( FACULTY_ID ) REFERENCES FACULTY ( FACULTY_ID ) ;
ALTER TABLE STUDENT_ATTENDANCE ADD CONSTRAINT STUDENT_ATTENDANCE_FK FOREIGN KEY ( STUDENT_ID ) REFERENCES STUDENT ( STUDENT_ID ) ;
ALTER TABLE STUDENT_COURSE ADD CONSTRAINT STUDENT_COURSE_FK FOREIGN KEY ( STUDENT_ID ) REFERENCES STUDENT ( STUDENT_ID ) ;
ALTER TABLE STUDENT_COURSE ADD CONSTRAINT STUDENT_COURSE_FKv2 FOREIGN KEY ( COURSE_ID ) REFERENCES COURSE ( COURSE_ID ) ;
ALTER TABLE STUDENT ADD CONSTRAINT STUDENT_FK FOREIGN KEY ( PARENT_ID ) REFERENCES PARENT_INFORMATION ( PARENT_ID ) ;

-- ALTERING THE FACULTY_LOGIN TABLE FOR DEFAULT DATES
ALTER TABLE FACULTY_LOGIN MODIFY (LOGIN_DATE DATE DEFAULT SYSDATE);

-- ALTERING THE STUDENT TABLE FOR UNIQUE EMAIL ADDRESS
ALTER TABLE STUDENT ADD (EMAIL_ADDR VARCHAR2 (100) UNIQUE );