/* Created by Torri Baptista, This Script will access the student and falculties accounts 
while checking the for added data that has been imported by falcuty */

SELECT *
FROM STUDENT ;

SELECT *
FROM EXAM_RESULT ;

SELECT DISTINCT FIRST_NAME, GRADE + 7
FROM STUDENT, EXAM_RESULT ;

SELECT  STUDENT_ID ||': This Email Address of '||FIRST_NAME ||' IS '|| EMAIL_ADDR AS STUDENT_EMAIL
FROM STUDENT ;

SELECT *
FROM COURSE NATURAL JOIN ACADEMIC_SESSION
WHERE SESSION_ID = 100 ;

SELECT *
FROM COURSE
WHERE DEPARTMENT_ID BETWEEN 20 AND 30 ;

SELECT *
FROM STUDENT
WHERE FIRST_NAME LIKE 'M%' ;

SELECT *
FROM COURSE NATURAL JOIN ACADEMIC_SESSION 
WHERE SESSION_ID = 200 ;


