/*Students who are eligible to take the upcomimg exams*/
SELECT FIRST_NAME, ELIGIBILITY_FOR_EXAMS
FROM STUDENT_ATTENDANCE NATURAL JOIN STUDENT ;

/* The Studendens whom grades are larger than 70% on the Test*/
SELECT DISTINCT STUDENT_ID, FIRST_NAME, GRADE 
FROM EXAM_RESULT NATURAL JOIN STUDENT
WHERE GRADE > 70  ;

/* Highest grade from the student Nina */
SELECT FIRST_NAME, GRADE, EXAM_NAME
FROM STUDENT, EXAM_RESULT CROSS JOIN EXAM_TYPE 
WHERE FIRST_NAME = 'NINA' AND GRADE >= '99';

SELECT FIRST_NAME, AVG(GRADE) AS STUDENT_AVG_GRADE
FROM STUDENT NATURAL JOIN EXAM_RESULT
GROUP BY FIRST_NAME 
ORDER BY AVG(GRADE) DESC;

SELECT AVG(GRADE) AS "OOAD_AVERAGE_GRADE"
FROM COURSE NATURAL JOIN EXAM_RESULT 
WHERE COURSE_NAME = 'OOAD' ;
